name: deploy cave game
on:
  push:
    branches: 
      - main
    paths:
      - cave-game/**
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Store your private key as a secret

      - name: Restart server
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_TARGET }} "bash deploy_serve.sh"
