name: deploy cave game
on:
  push:
    branches: 
      - sean-get-secrets
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SHEEP_A: ${{ secrets.SSH_PRIVATE_KEY }} # Store your private key as a secret
          SHEEP_B: ${{ secrets.SSH_TARGET }} # Store your private key as a secret
        run: node test.js
        
