name: remind nerds
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: figure out who didnt commit yet
        run: |
          
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
