name: Revert Commit if export is added to escape/GAMER.ts

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  check-and-revert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for added lines containing export in escape/GAMER.ts
      id: check-export
      run: |
        # Check if escape/GAMER.ts was modified in the incoming commit
        if git show --pretty=format:'' --name-only HEAD | grep -q 'escape/GAMER.ts'; then
          # Check for added lines containing the word "export"
          if git diff HEAD~1 HEAD -- escape/GAMER.ts | grep -q '^\+.*export'; then
            echo "Added line containing 'export' found in escape/GAMER.ts"
            echo "::set-output name=revert::true"
          else
            echo "No added lines containing 'export' found in escape/GAMER.ts"
            echo "::set-output name=revert::false"
          fi
        else
          echo "escape/GAMER.ts not modified in the incoming commit"
          echo "::set-output name=revert::false"
        fi

    - name: Revert the incoming commit with custom message
      if: steps.check-export.outputs.revert == 'true'
      run: |
        git revert HEAD --no-edit -m "FUCK YOU; STOP TRYING TO EXPORT FROM GAMER"
        git push origin HEAD