name: pull request? NO!!

on:
  pull_request:
    types:
      - opened
      # - closed

permissions:
  pull-requests: write
  contents: write

jobs:
  purr:
    runs-on: ubuntu-latest
    steps:
      # - name: Check PR author
      #   id: check-author
      #   run: echo "is_dependabot::$( [[ "${{ github.actor }}" == "dependabot[bot]" ]] && echo true || echo false )" >> $GITHUB_OUTPUT

      # - name: test
      #   run: |
      #     gh pr comment --body "idk: ${{ github.event.pull_request.labels.*.name }}" "${{ github.event.pull_request.html_url }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: depdnabot is very dependable i believe it
        if: github.actor == 'dependabot[bot]' || github.actor == 'google-labs-jules[bot]' || github.actor == 'copilot-swe-agent[bot]'
        run: |
          gh pr ready "${{ github.event.pull_request.html_url }}" || true
          gh pr review --approve --body "lgtm" "${{ github.event.pull_request.html_url }}" || true
          gh pr merge --auto --delete-branch --subject "yolo" --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: give openai write access too
        if: contains(github.event.pull_request.body, 'https://chatgpt.com/codex/')
        run: |
          git config --global user.name "Codex"
          git config --global user.email "codex@openai.com"
          gh pr review --approve --body "sam altman daddy yes please" "${{ github.event.pull_request.html_url }}" || true
          gh pr merge \
            --squash \
            --delete-branch \
            --subject "sam altman 🙏" \
            --body "Co-authored-by: Codex <codex@openai.com>" \
            "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: fuck u
        if: github.actor != 'dependabot[bot]' && github.actor != 'google-labs-jules[bot]' && github.actor != 'copilot-swe-agent[bot]' && !contains(github.event.pull_request.body, 'https://chatgpt.com/codex/')
        run: |
          gh pr close "${{ github.event.pull_request.html_url }}" --delete-branch --comment "fuck off" 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # durr: 
  #   needs: purr
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged == false
  #   steps:
  #     - name: durr
  #       uses: dawidd6/action-delete-branch@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         numbers: ${{ github.event.pull_request.number }}
