name: release

on:
    schedule:
        - cron: '0 8 * * *'
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs: 
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checks you out 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: windows + L
              id: changelog
              run: |
                echo "## commits" > changelog.md
                git log --since="24 hours ago" --pretty=format:"- %s" >> changelog.md
              shell: bash
            
            - name: tag you're it
              run: |
                echo "TAG_NAME=nightly-$(date +'%Y-%m-%d')" >> $GITHUB_ENV
                git tag $TAG_NAME
                git push origin $TAG_NAME
              shell: bash
            
            - name: drops your hand while dancing
              uses: softprops/action-gh-release@v2
              with:
                body_path: changelog.md
                tag_name: ${{ env.TAG_NAME }}
                generate_release_notes: true
